#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────"
if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u abc)
User GID:    $(id -g abc)
───────────────────────────────────────
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
    echo '
╔═════════════════════════════════════════════════════════════════════════════╗
║                                                                             ║
║        Your Docker Host is running an outdated version of libseccomp        ║
║                                                                             ║
║    To fix this, please visit https://docs.linuxserver.io/faq#libseccomp     ║
║                                                                             ║
║                 Apps will not behave correctly without this                 ║
║                                                                             ║
╚═════════════════════════════════════════════════════════════════════════════╝
'
    sleep infinity
fi

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults
