#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    if [[ -n ${DISABLE_PACKAGE_CACHE} ]]; then
        if [[ -L $(which grep) ]]; then
            # BusyBox grep
            # shellcheck source=/dev/null
            ALPINE_VERSION=$(. /etc/os-release && echo "${VERSION_ID}" | grep -Eo '^\d\.\d+')
        else
            # GNU grep
            # shellcheck source=/dev/null
            ALPINE_VERSION=$(. /etc/os-release && echo "${VERSION_ID}" | grep -Po '^\d\.\d+')
        fi

        if [[ -n "${ALPINE_VERSION}" ]] && [[ ! -L /etc/apk/cache ]]; then
            mkdir -p "/modcache/alpine/${ALPINE_VERSION}"
            ln -s "/modcache/alpine/${ALPINE_VERSION}" /etc/apk/cache
        fi
    fi
fi
