#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "$(find /var/run/s6/container_environment/*"FILE__"* -maxdepth 1 2>/dev/null)" ]]; then
    for FILENAME in /var/run/s6/container_environment/*; do
        if [[ "${FILENAME##*/}" == "FILE__"* ]]; then
            SECRETFILE=$(cat "${FILENAME}")
            if [[ -f ${SECRETFILE} ]]; then
                FILESTRIP=${FILENAME//FILE__/}
                cat "${SECRETFILE}" >"${FILESTRIP}"
                echo "[env-init] ${FILESTRIP##*/} set from ${FILENAME##*/}"
            else
                echo "[env-init] cannot find secret in ${FILENAME##*/}"
            fi
        fi
    done
fi
