#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# /defaults/crontabs is for user customizable crontabs and they take priority over /etc/crontabs
# /etc/crontabs is for non-user customizable crontabs
# /config/crontabs is only imported if /defaults/crontab is present in image
# in RO environments, no import is done, only /etc/crontabs is active
for cron_user in abc root; do
    if [[ -f "/defaults/crontabs/${cron_user}" ]] && [[ -z ${LSIO_READ_ONLY_FS} ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
        # make folders
        mkdir -p \
            /config/crontabs

        # if crontabs do not exist in config
        if [[ ! -f "/config/crontabs/${cron_user}" ]]; then
            # copy crontab from image defaults (using -n, do not overwrite an existing file)
            cp -n "/defaults/crontabs/${cron_user}" /config/crontabs/
        fi

        # import user crontabs
        crontab -u "${cron_user}" "/config/crontabs/${cron_user}"

        lsiown -R abc:abc /config/crontabs
    fi
done
