#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" linuxserver.io
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" linuxserver.io
usermod -o -u "$PUID" abc

echo '
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u linuxserver.io)
User gid:    $(id -g linuxserver.io)
-------------------------------------
"
chown linuxserver.io:linuxserver.io /app
chown linuxserver.io:linuxserver.io /config
chown linuxserver.io:linuxserver.io /defaults
